name: CI

#on: [push]

# 在master分支发生push事件时触发。
on:
  push:
    branches:
      - master

env: # 设置环境变量
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用该时区时间）

jobs:
  build: # 自定义名称
    runs-on: ubuntu-latest # 运行在虚拟机环境ubuntu-latest
  
    strategy:
        matrix:
          node-version: [16.x]
    
    steps:
        - name: Checkout # 步骤1
          uses: actions/checkout@v1 # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions
        - name: Use Node.js ${{ matrix.node-version }} # 步骤2
          uses: actions/setup-node@v1 # 作用：安装nodejs
          with:
            node-version: ${{ matrix.node-version }} # 版本
        - name: run deploy.sh # 步骤3 部署github
          env: # 设置环境变量
            GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # toKen私密变量
          run: npm install && npm run deploy # 执行的命令
        - name: SSH Deploy
          uses: easingthemes/ssh-deploy@v2.2.11
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
            ARGS: '-avzr --delete'
            SOURCE: 'docs/.vuepress/dist/*'
            REMOTE_HOST: ${{ secrets.SERVER_HOST }}
            REMOTE_USER: 'root'
            TARGET: '/var/www/hub-blog/'
        - name: Remove local dist folder
        run: |
          rm -rf docs/.vuepress/dist